language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e gin_tune
  - python ray/python/ray/setup-dev.py --yes 
  - pip install -e .
  - sudo apt-get install graphviz
# command to run tests
script:
  - ./tests.sh
services: mongodb
