language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e gin-config
  - python ray/python/ray/setup-dev.py 
  - pip install -e .
# command to run tests
script:
  - ./tests.sh
services: mongodb
